apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: kube-system
data:
  ## Can be configured at runtime
  bpfman.agent.image: localhost:5000/bpfman-agent:latest
  bpfman.image: localhost:5000/bpfman:latest
  ## Can be set to "info", "debug", or "trace"
  bpfman.agent.log.level: "info"
  ## See https://docs.rs/env_logger/latest/env_logger/ for configuration options
  bpfman.log.level: "info"
